name: connect

description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 여기에 의존성 추가
  http: ^0.13.6
  provider: ^6.0.5
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.0.0
  flutter_image_compress: ^2.4.0
  flutter_markdown: ^0.6.18
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  image_picker: ^0.8.7+4
  path: ^1.8.3
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
